#ifndef KNOWYOURKNOWLEDGE_COMMANDLINEPROCESSORCONSTANTS_H
#define KNOWYOURKNOWLEDGE_COMMANDLINEPROCESSORCONSTANTS_H

const char* ADD_NOTE_NAME = "add";

const char* READ_FILE_NAME = "config.txt";
const char* SAVE_FILE_PATH_NAME = "../../resources/config.txt";

#endif //KNOWYOURKNOWLEDGE_COMMANDLINEPROCESSORCONSTANTS_H
