#ifndef KNOWYOURKNOWLEDGE_COMMANDLINEPROCESSORCONSTANTS_H
#define KNOWYOURKNOWLEDGE_COMMANDLINEPROCESSORCONSTANTS_H

const char* ADD_NOTE_NAME = "add";

const char* COLLECTION_KEY = "current_collection";
const char* CONFIG_FILE_PATH_NAME = "./resources/config.txt";

#endif //KNOWYOURKNOWLEDGE_COMMANDLINEPROCESSORCONSTANTS_H
